# Generated by Django 4.0.2 on 2022-02-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Imovei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_imovel', models.IntegerField()),
                ('valor', models.FloatField()),
                ('quartos', models.IntegerField()),
                ('tamanho', models.FloatField()),
                ('rua', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('V', 'Venda'), ('A', 'Aluguel')], max_length=1)),
                ('tipo_imovel', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('L', 'Lote')], max_length=1)),
                ('numero', models.IntegerField()),
                ('descricao', models.TextField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.cidade')),
                ('imagens', models.ManyToManyField(to='plataforma.Imagem')),
            ],
        ),
    ]
