# Generated by Django 4.0.2 on 2022-02-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovei',
            name='garagem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovei',
            name='codigo_imovel',
            field=models.IntegerField(unique=True),
        ),
    ]
