# Generated by Django 4.0.2 on 2022-02-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_imovei_banheiros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovei',
            old_name='garagem',
            new_name='garagens',
        ),
    ]
