# Generated by Django 4.0.2 on 2022-02-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_rename_garagem_imovei_garagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovei',
            name='codigo_imovel',
        ),
    ]
