# Generated by Django 4.0.2 on 2022-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_remove_imovei_codigo_imovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameInput', models.CharField(max_length=100)),
                ('emailinput', models.EmailField(max_length=254)),
                ('mensagemInput', models.TextField()),
            ],
        ),
    ]
