# Generated by Django 4.0.2 on 2022-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_rename_emailinput_contato_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
