# Generated by Django 4.0.2 on 2022-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_contato_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
