# Generated by Django 4.0.2 on 2022-03-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_imovei_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovei',
            name='imagens',
        ),
    ]
