# Generated by Django 4.0.2 on 2022-03-07 19:28

from django.db import migrations, models
import plataforma.models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_remove_imovei_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovei',
            name='imagens',
            field=models.ImageField(default=1, upload_to='', verbose_name=plataforma.models.Imagem),
            preserve_default=False,
        ),
    ]
