# Generated by Django 4.0.2 on 2022-03-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_imovei_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovei',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='imovei',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imovei',
            name='imagens',
            field=models.ManyToManyField(to='plataforma.Imagem'),
        ),
    ]
