# Generated by Django 4.0.2 on 2022-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_remove_imovei_bairro_remove_imovei_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovei',
            name='bairro',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
