# Generated by Django 4.0.2 on 2022-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_imovei_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovei',
            name='tipo_imovel',
            field=models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('L', 'Lote'), ('IC', 'Imóvel_Comercial'), ('IR', 'Imóvel_Rural'), ('T', 'Temporada')], max_length=2),
        ),
    ]
