# Generated by Django 4.0.2 on 2022-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_alter_imovei_tipo_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovei',
            name='tipo',
            field=models.CharField(choices=[('V', 'Venda'), ('A', 'Aluguel'), ('T', 'Temporada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='imovei',
            name='tipo_imovel',
            field=models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('L', 'Lote'), ('IC', 'Imóvel_Comercial'), ('IR', 'Imóvel_Rural')], max_length=2),
        ),
    ]
